Pediatrics module first version
BIH-CEI/napkon-pediatrics pull request #8
Opened 2021-11-11 21:36 UTC by glichtner

2021-11-11 21:37 UTC, glichtner commented
3 value sets and one profile is still missing, but the existing profiles and value sets can be reviewed already. The remaining vs/profile will be added to this PR once available.

2021-11-14 15:07 UTC, glichtner commented
missing profiles and value sets added

2021-11-23 16:43 UTC, ylboerner requested changes
Great PR already! I added around 30 remarks, some of them specific change requests, some of them openers for a discussion. Looking forward to the next review round!

2021-11-23 16:43 UTC, ylboerner commented on input/fsh/pediatrics/p-preadmission-medications.fsh
> +* code = $sct#281379000 "Pre-admission (qualifier value)"
[This code ](https://browser.ihtsdotools.org/?perspective=full&conceptId1=394829006&edition=MAIN/2021-07-31&release=&languages=en) is more suitable. 'Pre-admission' is not really applicable here.

2021-11-23 16:57 UTC, glichtner commented on input/fsh/pediatrics/p-complications.fsh
> +* extension[dueTo].valueCodeableConcept = $sct#840539006 "Disease caused by Severe acute respiratory syndrome coronavirus 2 (disorder)"
Not sure I understand correctly: This (840539006) _is_ the code for COVID-19, see [here](https://browser.ihtsdotools.org/?perspective=full&conceptId1=840539006&edition=MAIN/2021-07-31&release=&languages=en)

2021-11-23 17:03 UTC, glichtner commented on input/fsh/pediatrics/p-pediatric-medication.fsh
> +// TODO: Mention in IG that "Anwendungsdauer" is coded by effectivePeriod
No and it will only be done when we write the implementation guide after the profiles have been finished, so I prefer to leave it there until this has been done.

2021-11-23 19:36 UTC, glichtner commented on input/fsh/pediatrics/cs-napkon-pediatrics.fsh
> +* #000010 "Mammalian target of rapamycin (mTOR)-Kinase inhibitor"
agreed & changed

2021-11-23 19:37 UTC, glichtner commented on input/fsh/pediatrics/p-chronic-hematologic-diseases.fsh
> +Description: "Chronic Hematoloogic diseases as a risk factor for a severe course of an infection with SARS-CoV-2 in the context of pediatrics"
corrected

2021-11-23 19:37 UTC, glichtner commented on input/fsh/pediatrics/p-chronic-hematologic-diseases.fsh
> +* code.coding[sct] from ChronicHematoloogicDiseases (required)
corrected

2021-11-23 19:38 UTC, glichtner commented on input/fsh/pediatrics/p-chronic-hematologic-diseases.fsh
> +// Author: Thomas Haese
done

2021-11-23 19:39 UTC, glichtner commented on input/fsh/pediatrics/p-gastrointestinal-diseases-pediatrics.fsh
> +// Author: Thomas Haese
done

2021-11-23 19:40 UTC, glichtner commented on input/fsh/pediatrics/p-imaging-procdures.fsh
> +//* code.coding[dicom] = $dicom#CT "Computed Tomography"
it is actually required because we're dealing with PET/CT here -- uncommented it

2021-11-23 19:43 UTC, glichtner commented on input/fsh/pediatrics/p-pediatric-medication.fsh
> +Description: "Prescription of a medication or consumption by a pediatric patient."
changed the description

2021-11-23 19:43 UTC, glichtner commented on input/fsh/pediatrics/p-preadmission-medications.fsh
> +Description: ""
done

2021-11-23 19:44 UTC, glichtner commented on input/fsh/pediatrics/p-preadmission-medications.fsh
> +* code = $sct#281379000 "Pre-admission (qualifier value)"
changed accordingly

2021-11-23 19:44 UTC, glichtner commented on input/fsh/pediatrics/p-thoracic-drainage.fsh
> +Description: "Application of a thoraric drainage"
changed

2021-11-23 19:47 UTC, glichtner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +// D70-D77 Sonstige Krankheiten des Blutes und der blutbildenden Organe
It's just the description of the ICD codes that are captured by the regex above. I prefer to leave it here because it's much easier to see if the codes are correct (or at least what they mean) than just seeing the regex and having to look up what D50-D79 actually is. What do you think?

2021-11-23 19:47 UTC, glichtner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases.fsh
> +Description: "Chronic hematoloogic diseases the context of pediatrics and Covid-19"
corrected

2021-11-23 21:02 UTC, glichtner commented on input/fsh/pediatrics/p-bacterial-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
added observation category, but still using the specialty as the category - that is what is being done in GECCO (using medical specialties in Condition.category) - let's discuss in our meeting

2021-11-23 21:08 UTC, glichtner commented on input/fsh/pediatrics/p-congenital-disease.fsh
> +  * coding[complication] = $sct#394537008 "Pediatric specialty (qualifier value)"
- isn't the code system you referenced used for Observation rather than Condition?
- GECCO uses the medical specialty in Condition.category, that's what I've done too - let's discuss in our meeting

2021-11-23 21:08 UTC, glichtner commented on input/fsh/pediatrics/p-covid-19-symptoms.fsh
> +* category.coding[pediatrics] = $sct#394537008 "Pediatric specialty (qualifier value)"
- isn't the code system you referenced used for Observation rather than Condition?
- GECCO uses the medical specialty in Condition.category, that's what I've done too - let's discuss in our meeting

2021-11-23 21:08 UTC, glichtner commented on input/fsh/pediatrics/p-fungal-infection.fsh
> +  * coding[infectiousDiseases] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
- isn't the code system you referenced used for Observation rather than Condition?

2021-11-23 21:08 UTC, glichtner commented on input/fsh/pediatrics/p-gastrointestinal-diseases-pediatrics.fsh
> +  * coding[gastroenterology].code 1.. MS
- isn't the code system you referenced used for Observation rather than Condition?

2021-11-23 21:09 UTC, glichtner commented on input/fsh/pediatrics/p-viral-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
- isn't the code system you referenced used for Observation rather than Condition?

2021-11-23 21:12 UTC, glichtner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +Description: "Chronic hematoloogic diseases in the context of pediatrics and Covid-19"
corrected

2021-11-23 21:12 UTC, glichtner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +Description: "Chronic hematoloogic diseases in the context of pediatrics and Covid-19"
corrected

2021-11-23 21:14 UTC, glichtner commented on input/fsh/pediatrics/p-covid-19-symptoms.fsh
> +* extension[dueTo].valueCodeableConcept = $sct#840539006 "Disease caused by Severe acute respiratory syndrome coronavirus 2 (disorder)"
Not sure I understand correctly: This (840539006) _is_ the code for COVID-19, see [here](https://browser.ihtsdotools.org/?perspective=full&conceptId1=840539006&edition=MAIN/2021-07-31&release=&languages=en)

2021-11-23 21:26 UTC, glichtner commented on input/fsh/pediatrics/p-fungal-infection.fsh
> +Title: "Fungal Infectin Confirmed"
corrected

2021-11-23 21:27 UTC, glichtner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +// D70-D77 Sonstige Krankheiten des Blutes und der blutbildenden Organe
see comment on other comment on the same file and lines

2021-11-26 09:01 UTC, ylboerner commented on input/fsh/pediatrics/p-bacterial-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
1. Correct, it is usually used for Observation but it can be used for Condition here as well!
2. Great!

2021-11-26 09:03 UTC, ylboerner commented on input/fsh/pediatrics/p-congenital-disease.fsh
> +  * coding[complication] = $sct#394537008 "Pediatric specialty (qualifier value)"
Correct, it is usually used for Observation but it can be used for Condition here as well!
Great!

2021-11-26 09:04 UTC, ylboerner commented on input/fsh/pediatrics/p-covid-19-symptoms.fsh
> +* category.coding[pediatrics] = $sct#394537008 "Pediatric specialty (qualifier value)"
1. Correct, it is usually used for Observation but it can be used for Condition here as well!
2. Yes, let's do that.

2021-11-26 09:05 UTC, ylboerner commented on input/fsh/pediatrics/p-pediatric-medication.fsh
> +// TODO: Mention in IG that "Anwendungsdauer" is coded by effectivePeriod
Agreed!

2021-11-26 09:17 UTC, ylboerner commented on input/fsh/pediatrics/p-viral-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
Yes, but it can be used here as well!

2021-11-26 09:24 UTC, ylboerner commented on input/fsh/pediatrics/vs-viral-infectious-diseases.fsh
> +* codes from system $sct where concept is-a #34014006 "Viral disease (disorder)" // für "Andere" (confirmed) und "Nein" (refuted) - TODO: OK?
Thanks for the thorough explanation. I concur with the approach 👍

2021-11-26 09:27 UTC, ylboerner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +// D70-D77 Sonstige Krankheiten des Blutes und der blutbildenden Organe
It should definitely relieve the reader of the burden to either figure out the regex or looking up the codes. Yes, let's leave it here.

2021-11-26 09:38 UTC, ylboerner commented on input/fsh/pediatrics/p-gastrointestinal-diseases-pediatrics.fsh
> +  * coding[gastroenterology].code 1.. MS
Yes, but it is allowed here as well 👍

2021-11-26 09:38 UTC, ylboerner commented on input/fsh/pediatrics/p-fungal-infection.fsh
> +  * coding[infectiousDiseases] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
Yes, but it is allowed here as well 👍

2021-11-26 09:40 UTC, ylboerner commented on input/fsh/pediatrics/p-complications.fsh
> +* extension[dueTo].valueCodeableConcept = $sct#840539006 "Disease caused by Severe acute respiratory syndrome coronavirus 2 (disorder)"
I skimmed over the profile too fast and stand corrected, thanks!

2021-11-26 09:41 UTC, ylboerner commented on input/fsh/pediatrics/vs-chronic-hematologic-diseases-icd.fsh
> +// D70-D77 Sonstige Krankheiten des Blutes und der blutbildenden Organe
Agreed and resolved!

2021-11-26 10:43 UTC, glichtner commented on input/fsh/pediatrics/p-imaging-procdures.fsh
> +// Author: Sally Brose
create ImagingStudy profile additionally

2021-11-26 10:44 UTC, glichtner commented on input/fsh/pediatrics/p-intensive-care-length.fsh
> +// Author: Gregor Lichtner
stick to Observation

2021-11-26 10:44 UTC, glichtner commented on input/fsh/pediatrics/p-total-length-of-stay.fsh
> +// Author: Gregor Lichtner
stick to observation

2021-11-29 08:43 UTC, glichtner commented on input/fsh/pediatrics/p-birth-height.fsh
> +* insert value-quantity(#cm)
we leave it at is to be consitent with GECCO

2021-11-29 09:39 UTC, glichtner commented on input/fsh/pediatrics/p-bacterial-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
added #laboratory

2021-11-29 09:42 UTC, glichtner commented on input/fsh/pediatrics/p-congenital-disease.fsh
> +  * coding[complication] = $sct#394537008 "Pediatric specialty (qualifier value)"
* added #laboratory
* left "pediatrics" as specialty as per our discussion

2021-11-29 09:44 UTC, glichtner commented on input/fsh/pediatrics/p-imaging-procdures.fsh
> +//* code.coding[dicom] = $dicom#CT "Computed Tomography"
removed dicom coding and valueset

2021-11-29 09:45 UTC, glichtner commented on input/fsh/pediatrics/p-viral-infection.fsh
> +  * coding[sct] = $sct#394807007 "Infectious diseases (specialty) (qualifier value)"
added #laboratory

2021-11-29 10:16 UTC, glichtner commented on input/fsh/pediatrics/p-imaging-procdures.fsh
> +// Author: Sally Brose
added PediatricImagingStudy profile

2021-11-29 10:42 UTC, glichtner commented
@ylboerner I've processed all remaining comments (addition of #laboratory to Condition.category, removal of separate DICOM codes for PT/CT study and addition of a profile on ImagingStudy). Can you check and approve? Thanks!

2021-12-02 17:15 UTC, ylboerner approved these changes

2021-12-02 17:19 UTC, merged